### ISSUE TITLE
Browser & Accessibility Testing

### ISSUE THREAD

**Issue by ishanb2001** [zannallan/web-design-2-independent-project#10]
<img width="1661" alt="Screen Shot 2020-12-07 at 10 00 33 AM" src="https://user-images.githubusercontent.com/55193891/101366631-29495b80-3873-11eb-9646-ff5393f1f3a0.png">

**Comment by zannallan** [comment]
Hi Ishan, I have completed the website entirely so it should be mobile-friendly now.
