### ISSUE TITLE
Speed Performance

### ISSUE THREAD

**Issue by Sophia-Villamayor** [zannallan/web-design-2-independent-project#4]
You have a score of 89 which is really good! Just some checks that Google is showing.
- The quality and size of the image need to be smaller/lower and I'm sure once you change those then all the other checks will be fixed too! 
<img width="776" alt="Screen Shot 2020-12-07 at 9 35 55 AM" src="https://user-images.githubusercontent.com/54897840/101363859-e46ff580-386f-11eb-9cf4-2ad8b1a15a17.png">
<img width="783" alt="Screen Shot 2020-12-07 at 9 36 01 AM" src="https://user-images.githubusercontent.com/54897840/101363861-e46ff580-386f-11eb-84bb-c921ef8dbc17.png">

**Comment by zannallan** [comment]
Thanks!
