### ISSUE TITLE
Desktop Chrome, Desktop Safari, Desktop Firefox

### ISSUE THREAD

**Issue by ishanb2001** [zannallan/web-design-2-independent-project#5]
I noticed that your site had a big white space gap under the footer. Also, make sure you add padding to some of your text/buttons so they aren't too close to the edge of the site.

White space under footer
![Screen Shot 2020-12-07 at 9 34 16 AM](https://user-images.githubusercontent.com/55193891/101363704-b4c0ed80-386f-11eb-93ce-4f1536b9fdfb.png)

**Comment by zannallan** [comment]
Those were the white social icons. They are visible and smaller now. lol
